### PR TITLE
Project parser

### PR DESCRIPTION
**Pull request by BoykoAlex**
Gradle Project Parser able to parse outside of Gradle Build Process.
This is part of the solution for https://github.com/openrewrite/rewrite-gradle-plugin/issues/217

### CODE REVIEW

**Comment by jkschneider** [comment]
Interfaces with single implementations are better off as just classes.

**Comment by BoykoAlex** [comment]
@jkschneider Gradle tooling model only allows interfaces for models to fetch, hence i had to create interfaces... but I'll have another look at it...

**Comment by shanman190** [comment]
I don't see how all of the `*Impl` or the model builder classes are relevant to building the `GradleProject` marker. All of that code is already fully functional and working today without these changes as is shown by the tooling model's usage within the rewrite-gradle tests.

To me it sounded more like your goal was being able to parse the Gradle project sources in the same manner as is performed by the `DefaultProjectParser` which shouldn't require any model changes at all to support the tooling API path.

**Comment by BoykoAlex** [comment]
The goal is not only to have a `ProjectParser` similar to `DefaultProjectParser` outside of Gradle build process. The goal is to re-use the new `ProjectParser` from **reqrite-gradle-tooling-model:parser** module in `DefaultProjectParser`. See https://github.com/openrewrite/rewrite-gradle-plugin/pull/238. Essentially factor out source parsing logic out of `DefaultProjectParser` into `ProjectParser` that could work outside and inside the Gradle Build process (independent of Gradle API). Thus changes to parsing logic would go into one and only place (rather than `DefaultProjectParser` in rewrite gradle plugin and `ProjectParser` in the tooling model seperately).

The new `ProjectParser` takes `GradleProjectData` interface as an input. The `GradleProjectData` extends existing `GradleProject`. It extends it because:
 - parser needs plugins and name to configuration data
 - parser creates `GradleProject` marker from the corresponding tooling api object which in my case would be `GradleProjectData`
- also added group and version to `GradleProject` but could be moved to `GradleProjectData` - parser needs this data

Note that `GradleProject` marker class does not implement `GradleProject` tooling interface and the same is true for method return types.
This is okay for the case of transferring an object from Gradle build process outside with the help of the tooling api. The `GradleProject` marker object was created from `org.gradle.api.Project` and although it does not derive  from tooling `GradleProject` it has kind of the same signature methods methods such that Gradle tooling is able to create a compatible to `GradleProject` tooling interface proxy object.
Now, if I was to use `GradleProject` (just simplifying from `GradleProjectData` that extends from `GradleProject`) tooling instance for the `ProjectParser` on the Gradle build side (`DefaultProjectParser` case) where would this instance come from? There is only code to produce the `GradleProject` marker from `org.gradle.api.Project`. The `GradleProject` tooling interface had no concrete subclasses. Therefore, I've decided to create `*Impl` POJOs to have a concrete implementation of `GradleProject` tooling interface that could be used for the case of the Gradle Build process side. The code creating `*Impl` POJOs and `GradleProject` marker objects was exactly the same hence I've removed the logic for creating `GradleProject` marker from `org.gradle.api.Project` in favour of creating *Impl` POJOs of `GradleProject` tooling interface since it works for the case of being inside and outside the GradleBuild and avoids code repetition.

The change to the existing tooling model is that support from creating `GradleProject` marker from `org.gradle.api.Project` is switched to creating `GradleProject` tooling POJO. The same goes for `GradleSettings`.

**Comment by BoykoAlex** [comment]
Tests are failing because first `./gradlew clean build publishMavenLocal -x test` needs to run i think and then tests would use  the plugin part from local repository...

**Comment by shanman190** [comment]
So the `GradleProject` marker was only ever intended to be created from within a Gradle context. Whether that was when running natively in the Gradle plugin via the `org.openrewrite.gradle.marker.GradleProjectBuilder` directly or via the tooling API integration via the `org.openrewrite.gradle.toolingapi.ToolingApiOpenRewriteModelPlugin.OpenRewriteModelBuilder` model builder which utilizes the same interface ultimately.

I don't think the intent has ever been to be able to or support attempting to create the marker from scratch from outside of a Gradle context. That said the `*Impl` classes are just a mirror image of the existing `GradleProject` marker and the rewrite-maven classes that it utilizes. This was so that the object serialization between the tooling API and the tooling plugin would function for a transport. If you wanted to build up the marker, you could do so via just the marker itself and the supporting classes from rewrite-maven without using any of the `*Impl` classes that have been defined here at all even from outside of the Gradle Tooling API like you described -- though I wouldn't personally advise doing that...

As far as the extraction of the `DefaultProjectParser`, it feels like the only aspect of trouble is extracting the facet of how to then provide the marker that represents the current project. In the rewrite-gradle-plugin, the marker could be generated from the project via the existing mechanism and passed down via the `GradleProjectData` while in other contexts the marker may be generated via the Tooling API then passed down via the same mechanism. This is just my opinion though.

**Comment by BoykoAlex** [comment]
I wonder if you @sambsnyd could have a look at this PR please :-) It's been opened for a while and I'd like to know if this is acceptable at all or might be acceptable with some changes. Thanks in advance for taking a look.

**Comment by sambsnyd** [comment]
Creating `GradleProject` markers outside the context of Gradle or its tooling API is a non-goal for us. If it's something you want to do go for it, the public constructor is right there, but there is little incentive for us to take ownership of that logic. There's regression risk and maintenance burden but no obvious upside. About the only change in here I am inclined to accept is adding group and version fields to the `GradleProject`.

**Comment by BoykoAlex** [comment]
@sambsnyd I wouldn't say that GradleProject marker is created outside of the Gradle build context... (or have I missed anything?)

Original code:
1. `org.openrewrite.gradle.marker.GradleProject` created from `org.gradle.api.Project` (note that the marker is not instance of `org.openrewrite.gradle.toolingapi.GradleProject`)
2. Gradle Tooling API spits out `org.openrewrite.gradle.toolingapi.GradleProject`
3. `org.openrewrite.gradle.marker.GradleProject` created from `org.openrewrite.gradle.toolingapi.GradleProject`

This is essentially the same in the implementation proposed in the PR:
1. `org.openrewrite.gradle.toolingapi.GradleProjectImpl` created from `org.gradle.api.Project` (note that it is instance of `org.openrewrite.gradle.toolingapi.GradleProject`)
2. Gradle Tooling API spits out `org.openrewrite.gradle.toolingapi.GradleProject`
3. `org.openrewrite.gradle.marker.GradleProject` created from `org.openrewrite.gradle.toolingapi.GradleProject`

Only 1 has a bit of a difference due to `GradleProjectData` extending `org.openrewrite.gradle.toolingapi.GradleProject`. I do not think that regression and maintenance burden argument applies much to the `GradleProject` changes. Anyway, we can debate more on the subject of those `*Impl` classes and `GradleProject` - this is really the least concern IMO.

Taking ownership of the new **parser** module may not be desired on the Rewrite side - yes.

The additional change to **rewrite-gradle-plugin** proposed in the PR: https://github.com/openrewrite/rewrite-gradle-plugin/pull/238 is risky and can have regressions and might seem like a maintenance burden. That PR removes the project sources parsing logic from `DefaultParser` and uses the new `ProjectParser` instead. The benefit is that parser logic would be changed in one place only. Don't think it'd be great if `DefaultParser` and `ProjectParser` would both live their own lives independently but for the sake of not intrpducing risky changes this PR can be omitted perhaps.

All of this does not come without the incentive though. The incentive is that all consumers of the parser would have the same markers such as `JavaProvenance`, `ProjectProvenance`, `GradleProject` and any other newly added or removed markers that come as "conventional markers" that all recipes can rely on. Otherwise these markers may vary depending on the project parser implementation.

**Pull request closed without merging**
