### PR TITLE
Do not throw TestAbortException from test deps

### PR DESCRIPTION
**Pull request by BoykoAlex**
The `TestAbortException` is coming from the `rewrite-test` or test scope dependencies.
It's best to throw a different kind of exception. Perhaps `IllegalStateException` will do fine.

### CODE REVIEW

**Comment by timtebeek** [comment]
Hi @BoykoAlex ; this was an intentional addition in https://github.com/openrewrite/rewrite-gradle-tooling-model/commit/a454cc96a6a8222df6690730e3c8ebce1628cd31 for folks who can not use the Gradle `withToolingAPI`, but would still like to run whatever other tests before they contribute; we saw that at a customer. As such we'd like to keep this to transparently not fail those tests, but skip them instead.

What's the reason you ended up here to make this change?

**Comment by BoykoAlex** [comment]
Now I have to pull in `opentest4j` on compile scope to avoid `ClassNotFoundException` for `TestAbortException`. I'm not using `org.openrewrite.gradle.toolingapi.OpenRewriteModelBuilder` on the test scope but on the compile scope and wouldn't want to pull in test dependencies on the compile scope. Currently I've added:
```
		<dependency>
			<groupId>org.opentest4j</groupId>
			<artifactId>opentest4j</artifactId>
			<version>1.3.0</version>
		</dependency>
```
but I'd rather not since it is a test lib...

**Comment by BoykoAlex** [comment]
Wonder if perhaps could declare that `OpenRewriteModel forProjectDirectory(File projectDir, @Nullable File buildFile, @Nullable String initScript)` can throw an `IOException` instead and just deal with it in the caller code such that a test would throw `TestAbortException` and other callers whatever is more apropriate...

**Comment by BoykoAlex** [comment]
@timtebeek yes, of course I can change the PR. Will do this either tonight or tomorrow in the AM

**Review by timtebeek — APPROVED** [review]

**Pull request merged**
